version: '3'
services:

  notion_service:
    environment:
      - KAFKA_CONECT_URL=${KAFKA_CONECT_URL}
      - NOTION_AUTH_TOKEN=${NOTION_AUTH_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}

    container_name: chapter_updater_notion_service
    build:
        context: notion-service
        dockerfile: ./dockerfile
    restart: always



  scraping_service:
    build:
        context: scraping-service
        dockerfile: ./dockerfile
    container_name: chapter_updater_scraping_service
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KAFKA_CONECT_URL=${KAFKA_CONECT_URL}
    restart: always


  notification_service:
   container_name: chapter_updater_notificaion_service
   restart: always

   build:
         context: notification-service
         dockerfile: ./dockerfile

  task_service:
    container_name: chapter_updater_task_service
    restart: always
    ports:
      - "3001:3001"
    build:
      context: task-service
      dockerfile: ./dockerfile
    env_file:
      - ./.env
    environment:
      - KAFKA_CONECT_URL=${KAFKA_CONECT_URL}
      - DATABASE_URL=${DATABASE_URL}
      - TELEGRAM_APP_ID=${TELEGRAM_APP_ID}
      - TELEGRANM_API_HASH=${TELEGRANM_API_HASH}
      - TELEGRAM_NOTIFICATION_BOT=${TELEGRAM_NOTIFICATION_BOT}
      - TELEGRAM_CHAT_ID=${TELEGRAM_CHAT_ID}


  kafka_ui:
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    environment:
      KAFKA_CLUSTERS_0_ZOOKEEPER: 139.144.184.180:2181
      KAFKA_CLUSTERS_0_NAME: cloud_broker
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: 139.144.184.180:9092







