version: '3'
services:

  document_service:
    environment:
      - KAFKA_CONECT_URL=${KAFKA_CONECT_URL}
      - NOTION_AUTH_TOKEN=${NOTION_AUTH_TOKEN}
      - NOTION_DATABASE_ID=${NOTION_DATABASE_ID}
    container_name: chapter_updater_document_service
    build:
        context: document-service
        dockerfile: ./dockerfile
    restart: always



  scraping_service:
    build:
        context: scraping-service
        dockerfile: ./dockerfile
    container_name: chapter_updater_scraping_service
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - KAFKA_CONECT_URL=${KAFKA_CONECT_URL}
    restart: always


  notification_service:
   container_name: chapter_updater_notificaion_service
   restart: always

   build:
         context: notification-service
         dockerfile: ./dockerfile






